language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-27
before_install:
    - yes | sdkmanager "platforms;android-28"
    - chmod +x gradlew
jdk:
    - openjdk8
script:
    - ./gradlew assemble check -x signArchives
notifications:
  email: false
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
